### PR TITLE
adds linter and prettier

### PR DESCRIPTION
**Pull request by about14sheep**
## Summary

adds basic linter and prettier for code formatting

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the api documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g new endpoint).
- [ ] This PR is a breaking change (e.g endpoints added or removed, endpoint parameters changes)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by RGBCube** [comment]
LGTM

**Review by joshwalters12 — COMMENTED** [review]
Can this be added to the CICD?

**Comment by RGBCube** [comment]
> Can this be added to the CICD?

wdym by the CICD? github workflows?

**Comment by joshwalters12** [comment]
> > Can this be added to the CICD?
> 
> 
> 
> wdym by the CICD? github workflows?

Yeah, the workflows

**Pull request merged**
